#!/usr/bin/env python3

import sys
import csv
from fuzzywuzzy import fuzz

_, tsi, fresh_camp = sys.argv

tsi_students = []
fresh_students = []

with open(tsi, 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        first = row['First'].strip()
        last = row['Last'].strip()

        if ',' in last:
            last_parts = last.split(',')
            if len(last_parts) != 2:
                print('Had an issue with: {}'.format(last))
                sys.exit(1)
            last = " ".join(reversed(last_parts))
            last = last.strip()

            last_parts = last.split(" ")
            if first == last_parts[0]:
                last = " ".join(last_parts[1:])

        tsi_students.append("{} {}".format(first, last))

with open(fresh_camp, 'r') as csvfile:
    reader = csv.DictReader(csvfile)
    for row in reader:
        last, first = row['NAME'].split(',')
        first = first.strip()
        last = last.strip()
        first_name_parts = first.split(' ')
        if len(first_name_parts) > 1:
            if len(first_name_parts[-1]) == 1:
                first = ' '.join(first_name_parts[0:-1])
        fresh_students.append("{} {}".format(first, last))

tsi_students.sort()
fresh_students.sort()

for stud1 in tsi_students:
    for stud2 in fresh_students:
        if stud1 == stud2:
            print("{} is found in both spreadsheets".format(stud1))
        elif fuzz.ratio(stud1, stud2) > 85:
            print("{} and {} might be same student".format(stud1, stud2))
